[versions]
retrofit = "2.9.0"
retrofit-serializationAdapter = "1.0.0"
okhttp = "4.10.0"
serialization = "1.5.0"
plugin-serialization = "1.8.22"
fragment = "1.6.0"


tossPay = "0.1.9"
compose-activity = "1.7.2"
compose-ui = "1.4.3"
compose-uiTooling = "1.4.3"
compose-foundation = "1.4.3"
compose-material = "1.4.3"
compose-viewModel = "2.6.1"

[libraries]
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment"}
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serializationAdapater = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serializationAdapter"}
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
toss-core = { module = "com.github.tosspayments:payment-sdk-android", version.ref = "tossPay"}

# compose
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity"}
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui"}
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-uiTooling"}
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation"}
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material"}
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewModel"}

[plugins]
plugin-serialization = { id = "plugin.serialization", version.ref = "serialization"}
